stages:
  - pre-build
  - build
  - deploy

variables:
  APP_SERVICE: sandbox-ujwalk-product-cards_app
  DOMAIN_DEVELOP: sandbox.dzangohq.org
  GIT_DEPTH: 1
  IMAGE: 139549850843.dkr.ecr.ap-southeast-1.amazonaws.com/sandbox/product-cards
  IMAGE_DEVELOP: $IMAGE:$VERSION.develop-ujwalk
  TAG: "$VERSION.0"
  VERSION: "0.1"

develop_prepare:
  artifacts:
    expire_in: 2 hours
    name: "{CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build
    when: on_success
  image: node:16-alpine
  script:
    - npx prettier --list-different .
    - yarn install --frozen-lockfile
    - yarn test --passWithNoTests
    - yarn build
  stage: pre-build
  tags:
    - docker

develop_build:
  environment: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cache=true
      --cache-repo=$IMAGE
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/devops/Dockerfile
      --destination $IMAGE_DEVELOP
  stage: build
  tags:
    - docker

develop_deploy:
  environment:
    name: develop
    url: https://ujwalk-product-cards.$DOMAIN_DEVELOP
  image: curlimages/curl
  needs:
    - job: develop_build
      artifacts: false
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - 'curl --fail -X POST
      --header "Accept: application/json"
      --header "authorization: Bearer $SWARMPIT_TOKEN_DEVELOP"
      "https://swarmpit.dzangohq.org/api/services/$APP_SERVICE/redeploy"'
  stage: deploy
  tags:
    - docker
  variables:
    GIT_STRATEGY: none
